[package]
name = "solutions"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
macros = { path = "../macros" }
substring = "1.4"
arr_macro = "0.1"
regex = "1"
num = "0.2"
multiarray = "0.1"